version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '02:00'
      timezone: 'Asia/Seoul'
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '02:00'
      timezone: 'Asia/Seoul'
    ignore:
      - dependency-name: '*storybook*'
        update-types: ['version-update:semver-major']
      - dependency-name: next
        update-types: ['version-update:semver-major']
      - dependency-name: react
        update-types: ['version-update:semver-major']
      - dependency-name: react-dom
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/react'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/react-dom'
        update-types: ['version-update:semver-major']
      - dependency-name: 'tailwindcss'
        update-types: ['version-update:semver-major']
    groups:
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production:
        dependency-type: production
        update-types:
          - patch
