name: Deployment

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: write
  pull-requests: write

jobs:
  deploy-storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          cache: true

      - name: Run build
        run: npm run build

      - name: Run chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: Comment on pull request
        uses: actions/github-script@v8
        with:
          script: |
            const issueNumber = (await github.rest.repos.listPullRequestsAssociatedWithCommit({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })).data[0].number;

            github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':rocket: storybook: ${{ steps.chromatic.outputs.storybookUrl }}'
            });
