name: Draft deployment

on:
  push:
    branches: ['main']

permissions:
  actions: read
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v4

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: creates output
        run: sh ./build.sh

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: herokwon
          destination-repository-name: inu-software-design-team-draft
          user-email: ${{ secrets.EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY

      # # 5. deploy-repo로 dispatch 이벤트 전송
      # - name: Trigger deploy-repo dispatch
      #   run: |
      #     curl -X POST https://api.github.com/repos/inu-software-design-team/deploy/dispatches \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer ${{ secrets.TOKEN_DEPLOY }}" \
      #       -H "Content-Type: application/json" \
      #       -d '{"event_type":"deploy_trigger"}'
